dist: trusty
sudo: false
git:
  depth: 1
language: generic
matrix:
  include:
    - env: CC=gcc-7 CXX=g++-7 AR=gcc-ar-7 NM=gcc-nm-7 RANLIB=gcc-ranlib-7
    - env: CC=gcc-5 CXX=g++-5 AR=gcc-ar-5 NM=gcc-nm-5 RANLIB=gcc-ranlib-5
    - language: python
      python: "3.6"
      name: Lint cmake files.
      install: pip3 install cmakelint
      script: scripts/lint.sh
  allow_failures:
    - name: Lint cmake files.
  fast_finish: true

install:
  # https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq zlib1g-dev libbz2-dev cmake
  - |
    if [[ "${CC}" =~ gcc- ]]; then
      echo "Installing ${CC}."
      sudo apt-get install -qq "${CC}"
    fi
  - |
    if [[ "${CXX}" =~ g\+\+- ]]; then
      echo "Installing ${CXX}."
      sudo apt-get install -qq "${CXX}"
    fi

before_script:
  - wget https://cmake.org/files/v3.15/cmake-3.15.2-Linux-x86_64.sh
  - sudo sh cmake-3.15.2-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir

script:
  - PATH=/usr/local/bin:$PATH
  - LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/lib:$LD_LIBRARY_PATH
  - mkdir build
  - pushd build
  # Set make -j N considering Travis providing 2 cores.
  # VERBOSE=1 to show the input commands in generatd Makefile for debug.
  - |
    cmake \
      -DCMAKE_BUILD_TYPE=RELEASE \
      -DFETCH_BOOST=TRUE \
      -DNO_RTM=TRUE \
      .. && \
    make -j 4 VERBOSE=1 && \
    make install && \
    ./src/salmon -h
  - |
    make CTEST_OUTPUT_ON_FAILURE=1 VERBOSE=1 test
  - popd

after_success:
  - ./scripts/push-binary.sh

after_failure:
  - echo "Failure"
  - ls -laR $TRAVIS_BUILD_DIR/build/Testing/
  - cat $TRAVIS_BUILD_DIR/build/Testing/Temporary/*
